"""add_is_admin_field

Revision ID: b044090790e7
Revises: 4a8896fb582b
Create Date: 2025-10-24 11:11:13.372954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b044090790e7'
down_revision = '4a8896fb582b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###

    # Назначаем первого пользователя администратором
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT id FROM users ORDER BY id ASC LIMIT 1"))
    first_user = result.fetchone()

    if first_user:
        conn.execute(
            sa.text("UPDATE users SET is_admin = 1 WHERE id = :user_id"),
            {"user_id": first_user[0]}
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
